#!/bin/bash
set -e

ICONPATH="$1"
NEWFILENAME="$(tr A-Z a-z <<< ${2:0:1})${2:1}"

./node_modules/@svgr/cli/bin/svgr \
  --no-svgo --replace-attr-values "#03082E"="{color}" < $ICONPATH \
  | sed "s/export default SvgComponent;/export default $2;/" \
  | sed "4d" \
  | sed "s/function SvgComponent(props) {/const $2 = ({ width, height, color }) => (/" \
  | sed 's/<svg width={24} height={24} viewBox="0 0 24 24" fill="none" {...props}>/<svg width={width || 24} height={height || 24} viewBox="0 0 24 24">/' \
  | sed '1h;1!H;$!d;g;s/\(.*\)}/\1/' \
  | pbcopy

echo "Copied icon component to clipboard ..."

pbpaste > src/icons/symbols/"$NEWFILENAME".tsx

echo "Created component in icons/symbols directory ..."