version: 2

jobs:
  preview:
    docker:
      - image: circleci/node:10.7.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Print out versions"
          command: |
            echo "node -v = $(node -v)"
            echo "npm -v = $(npm -v)"
            echo "yarn --version = $(yarn --version)"

      - restore_cache:
          key: node_modules-{{checksum "./package.json"}}-v3
      - run:
          name: "Install dependencies"
          command: |
            echo "# Top level package"
            npm i
      - save_cache:
          key: node_modules-{{checksum "./package.json"}}-v3
          paths:
            - "./node_modules"

      - run:
          name: "Build preview"
          command: npm run build-storybook
      - run:
          name: "Push preview to the cloud"
          command: |
            echo "* Installing amazon's cli..."
            sudo apt install -y python-pip python-dev
            sudo pip install -U 'awscli>=1.15'

            echo "* Copying to S3..."
            aws s3 sync storybook-static/ s3://ui-preview.density.rodeo/${CIRCLE_SHA1} --region us-east-1
      - run:
          name: "Post preview link to any pull requests commit is part of"
          command: |
            echo "* Posting status to commit ${CIRCLE_SHA1}"
            curl -X POST \
            -d "{\"state\":\"success\", \"context\": \"ci-preview\", \"target_url\": \"https://ui-preview.density.rodeo/${CIRCLE_SHA1}\"}" \
            -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
            https://api.github.com/repos/densityco/ui/statuses/${CIRCLE_SHA1}

  publish:
    docker:
      - image: circleci/node:10.7.0
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{checksum "./package.json"}}
      - run:
          name: "Install dependencies"
          command: |
            echo "# Top level package"
            npm i
      - run:
          name: "Add npm token to npmrc"
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: "Publish to npm registry"
          command: |
            set +e # This pemits the publich to fail if the version is the same as the previous commit
            npm publish
            set -e

workflows:
  version: 2
  npm-deployment:
    jobs:
      # For all pushes, build/deploy to `https://ui-preview.density.rodeo/SHA`
      - preview

      # Trunk is published to npm
      - publish:
          requires:
            - preview
          filters:
            branches:
              only: trunk
