version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.11

    steps:
      - run:
          name: "Add npm token to npmrc"
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            npm i
            for component in $(find components/ -maxdepth 1 -mindepth 1 -type d -printf "%f\n"); do
              # This isn't a component, but a template for `./make-component`
              if [ "$component" == "template" -o "$component" == "dist" ]; then
                continue
              fi

              cd components/$component
              npm i
              cd ../..
            done
      - run:
          name: "Build and publish the main package and each subcomponent to npm"
          command: |
            if [ "$CIRCLE_BRANCH" != "trunk" ]; then
              echo "* Skipping, branch is not the main repository branch."
              exit 0
            fi

            for component in $(find components/ -maxdepth 1 -mindepth 1 -type d -printf "%f\n"); do
              # This isn't a component, but a template for `./make-component`
              if [ "$component" == "template" -o "$component" == "dist" ]; then
                continue
              fi

              echo "****************"
              echo "* Publishing $component"
              echo "****************"
              set +e
              make publish COMPONENT=$component
              set -e
              echo
            done

            echo "****************"
            echo "* Publishing main package"
            echo "****************"
            set +e
            npm publish .
            set -e
      - run:
          name: "Build preview"
          command: npm run build-storybook
      - run:
          name: "Push preview to the cloud"
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
            aws s3 sync storybook-static/ s3://ui-preview.density.rodeo/$CIRCLE_BRANCH --region us-east-1
      - run:
          name: "Post preview link to any pull requests commit is part of"
          command: |
            echo "* Posting status to commit ${CIRCLE_SHA1}"
            curl -X POST \
            -d "{\"state\":\"success\", \"context\": \"ci-preview\", \"target_url\": \"https://ui-preview.density.rodeo/$CIRCLE_BRANCH\"}" \
            -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
            https://api.github.com/repos/densityco/dashboard/statuses/${CIRCLE_SHA1}
