version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.11

    steps:
      - run:
          name: "Add npm token to npmrc"
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            npm i
            for component in $(find components/ -maxdepth 1 -mindepth 1 -type d -printf "%f\n"); do
              # This isn't a component, but a template for `./make-component`
              if [ "$component" == "template" -o "$component" == "dist" ]; then
                continue
              fi

              cd components/$component
              npm i
              cd ../..
            done
      - run:
          name: "Build and publish the main package and each subcomponent to npm"
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              echo "* Skipping, branch is not the main repository branch."
              exit 0
            fi

            for component in $(find components/ -maxdepth 1 -mindepth 1 -type d -printf "%f\n"); do
              echo "****************"
              echo "* Publishing $component"
              echo "****************"
              set -x
              make publish COMPONENT=$component
              set +x
              echo
            done

            echo "****************"
            echo "* Publishing main package"
            echo "****************"
            npm publish .
      - run:
          name: "Build preview"
          command: |
            npm run build-storybook

            # Bug in react storybook that adds undefined to the page?
            sed -i bak 's/undefined//' storybook-static/index.html && rm storybook-static/index.html.bak
      - run:
          name: "Push preview to the cloud"
          command: |
            sudo apt-get update
            sudi apt-get install -y awscli
            aws s3 sync build/ s3://ui-preview.density.rodeo/$CIRCLE_BRANCH --region us-east-1
      - run:
          name: "Post preview link to any pull requests commit is part of"
          command: |
            # Post a link to the branch as a comment in the PR
            echo "* Pull requests this commit is part of: $CI_PULL_REQUESTS"
            export IFS=","
            for pr in $CI_PULL_REQUESTS; do
              num="$(echo $pr | awk -F'/' '{ print $NF }')"
              if [ -z \
                "$(curl -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
                https://api.github.com/repos/densityco/ui/issues/$num/comments \
                | jq .[].user.login \
                | grep density-machine-user)" ]; then

                curl -X POST \
                -d "{\"body\": \"Storybook preview: https://ui-preview.density.rodeo/$CIRCLE_BRANCH\"}" \
                -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
                https://api.github.com/repos/densityco/ui/issues/$num/comments

              fi
            done
